---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: external-http
  # annotations:
  #   networking.gke.io/certmap: airel-cert-map
spec:
  # This GatewayClass uses a global external Application Load Balancer.
  gatewayClassName: gke-l7-global-external-managed
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      options:
        networking.gke.io/pre-shared-certs: mcrt-86effbf8-d95d-49db-bb65-f48d4bfc01be

  - name: http
    protocol: HTTP
    port: 80
  
  - name: airel
    protocol: HTTP
    port: 8501

  # addresses:
  # - type: NamedAddress
  #   value: "airel-ip"



# Status:
#   Addresses:
#     Type:   IPAddress
#     Value:  34.120.42.214