---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: airel-routes
spec:
  parentRefs:
  # Bind the route to the 'external-http' Gateway.
  - kind: Gateway
    name: external-http
  hostnames:
  - "airel.jawadtahir.de"
  rules:
  # Default rule for airel.jawadtahir.de that sends traffic to the streamlit-frontend-service.
  - backendRefs:
    - name: streamlit-frontend-service
      port: 8501
  # # Match requests with the "env: canary" header and send them to the store-v2 service.
  # - matches:
  #   - headers:
  #     - name: env
  #       value: canary
  #   backendRefs:
  #   - name: store-v2
  #     port: 8080
  # # Match requests with the path "/de" and sends them to the store-german service.
  # - matches:
  #   - path:
  #       value: /de
  #   backendRefs:
  #   - name: store-german
  #     port: 8080