---
apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
type: Opaque
stringData:
  OPENAI_API_KEY: "OPENAI_API_KEY_VALUE_HERE"  # Replace with your actual key


---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: airel-certificate
spec:
  domains:
    - "YOUR_DOMAIN_HERE"  # Replace with your actual domain, e.g., airel.example.com